### ISSUE TITLE
Examples don't run

### ISSUE THREAD

**Issue by perplexes** [nakajima/sinatras-hat#3]
The examples don't run, and complain that the method #mount is missing. It looks like a delegator issue, since Sinatra has explicit methods it allows Object to delegate to (when you're in Object scope like your examples are). See http://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1108-1124.

You can fix this by adding "Sinatra::Delegator.delegate(:mount)" to the end of extendor.rb.

**Comment by nakajima** [comment]
Hmm, the specs seem to run for me. Can you copy and paste your output when you try?

**Comment by perplexes** [comment]
Er, I didn't mean the specs, I meant the simple-app.rb in the examples directory. The other example apps run, but I hadn't tried them until now :)

```
~/projects/github/sinatras-hat/example(master) $ ruby simple-app.rb
simple-app.rb:4: undefined method `mount' for main:Object (NoMethodError)
simple-app.rb:4: undefined method `mount' for main:Object (NoMethodError)
```

If you apply this patch: http://gist.github.com/283885

Then you'll get:

```
~/projects/github/sinatras-hat/example(master) $ ruby simple-app.rb
>> route for Post destroy:  DELETE  /posts/:id
>> route for Post new:  GET /posts/new
>> route for Post update:   PUT /posts/:id
>> route for Post edit: GET /posts/:id/edit
>> route for Post show: GET /posts/:id
>> route for Post create:   POST    /posts
>> route for Post index:    GET /posts
~/projects/github/sinatras-hat/example(master) $
```

Which is closer, but still doesn't start sinatra. Anyway, it's just surprising that #mount doesn't get delegated to Object scope. I should provide a test for it :)

**Comment by flazz** [comment]
i also had to add that line to make my app start. i'm using sinatra 1.0 on osx with bundler
